version: "3"

services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'renovation-api'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3300:3306
    volumes:
      - ./.mysql/data:/var/lib/mysql/

volumes:
  db:
